# Generated by Django 5.0.2 on 2024-04-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hindsight', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnsubscribedEmails',
        ),
    ]
