# Generated by Django 5.0.2 on 2024-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hindsight', '0002_delete_unsubscribedemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedemails',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
