# Generated by Django 5.0.2 on 2024-04-22 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hindsight', '0003_alter_subscribedemails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='indexparcel',
            name='parcels',
        ),
        migrations.DeleteModel(
            name='SubscribedEmails',
        ),
        migrations.DeleteModel(
            name='IndexParcel',
        ),
    ]
